//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercuryFitnessHubMain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityMaster
    {
        public System.Guid inEntityId { get; set; }
        public int autoEntityId { get; set; }
        public Nullable<int> autoEntityTypeId { get; set; }
        public string stEntityName { get; set; }
        public string stEntityCode { get; set; }
        public Nullable<int> inPEntityId { get; set; }
        public string stName { get; set; }
        public string stAddress { get; set; }
        public Nullable<int> inGender { get; set; }
        public string stEmailId { get; set; }
        public string stContactNo { get; set; }
        public string stFingureId { get; set; }
        public string stUserName { get; set; }
        public byte[] stPassword { get; set; }
        public string stRemark { get; set; }
        public Nullable<decimal> dbSalary { get; set; }
        public Nullable<System.DateTime> dtJoiningDate { get; set; }
        public Nullable<System.DateTime> dtResignDate { get; set; }
        public Nullable<bool> flgIsActive { get; set; }
        public bool flgIsDeleted { get; set; }
        public string stInsUser { get; set; }
        public System.DateTime dtInsDate { get; set; }
        public string stInsTerm { get; set; }
        public string stUpdUser { get; set; }
        public Nullable<System.DateTime> dtUpdDate { get; set; }
        public string stUpdTerm { get; set; }
    }
}
