//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercuryFitnessHubMain.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MercuryFitnessHubEntitiess1 : DbContext
    {
        public MercuryFitnessHubEntitiess1()
            : base("name=MercuryFitnessHubEntitiess1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EntityMaster> EntityMasters { get; set; }
        public virtual DbSet<EntityTypeMaster> EntityTypeMasters { get; set; }
        public virtual DbSet<EntityMappingDetail> EntityMappingDetails { get; set; }
    }
}
