#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercuryFitnessHubMain
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MercuryFitnessHub")]
	public partial class FitnessHubDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEntityMaster(EntityMaster instance);
    partial void UpdateEntityMaster(EntityMaster instance);
    partial void DeleteEntityMaster(EntityMaster instance);
    #endregion
		
		public FitnessHubDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["MercuryFitnessHubConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public FitnessHubDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FitnessHubDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FitnessHubDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FitnessHubDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<EntityMaster> EntityMasters
		{
			get
			{
				return this.GetTable<EntityMaster>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EntityMaster")]
	public partial class EntityMaster : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _inEntityId;
		
		private int _autoEntityId;
		
		private System.Nullable<int> _autoEntityTypeId;
		
		private string _stEntityName;
		
		private string _stEntityCode;
		
		private System.Nullable<int> _inPEntityId;
		
		private string _stName;
		
		private string _stAddress;
		
		private System.Nullable<int> _inGender;
		
		private string _stEmailId;
		
		private string _stContactNo;
		
		private string _stFingureId;
		
		private string _stUserName;
		
		private System.Data.Linq.Binary _stPassword;
		
		private string _stRemark;
		
		private System.Nullable<decimal> _dbSalary;
		
		private System.Nullable<System.DateTime> _dtJoiningDate;
		
		private System.Nullable<System.DateTime> _dtResignDate;
		
		private System.Nullable<bool> _flgIsActive;
		
		private bool _flgIsDeleted;
		
		private string _stInsUser;
		
		private System.DateTime _dtInsDate;
		
		private string _stInsTerm;
		
		private string _stUpdUser;
		
		private System.Nullable<System.DateTime> _dtUpdDate;
		
		private string _stUpdTerm;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OninEntityIdChanging(System.Guid value);
    partial void OninEntityIdChanged();
    partial void OnautoEntityIdChanging(int value);
    partial void OnautoEntityIdChanged();
    partial void OnautoEntityTypeIdChanging(System.Nullable<int> value);
    partial void OnautoEntityTypeIdChanged();
    partial void OnstEntityNameChanging(string value);
    partial void OnstEntityNameChanged();
    partial void OnstEntityCodeChanging(string value);
    partial void OnstEntityCodeChanged();
    partial void OninPEntityIdChanging(System.Nullable<int> value);
    partial void OninPEntityIdChanged();
    partial void OnstNameChanging(string value);
    partial void OnstNameChanged();
    partial void OnstAddressChanging(string value);
    partial void OnstAddressChanged();
    partial void OninGenderChanging(System.Nullable<int> value);
    partial void OninGenderChanged();
    partial void OnstEmailIdChanging(string value);
    partial void OnstEmailIdChanged();
    partial void OnstContactNoChanging(string value);
    partial void OnstContactNoChanged();
    partial void OnstFingureIdChanging(string value);
    partial void OnstFingureIdChanged();
    partial void OnstUserNameChanging(string value);
    partial void OnstUserNameChanged();
    partial void OnstPasswordChanging(System.Data.Linq.Binary value);
    partial void OnstPasswordChanged();
    partial void OnstRemarkChanging(string value);
    partial void OnstRemarkChanged();
    partial void OndbSalaryChanging(System.Nullable<decimal> value);
    partial void OndbSalaryChanged();
    partial void OndtJoiningDateChanging(System.Nullable<System.DateTime> value);
    partial void OndtJoiningDateChanged();
    partial void OndtResignDateChanging(System.Nullable<System.DateTime> value);
    partial void OndtResignDateChanged();
    partial void OnflgIsActiveChanging(System.Nullable<bool> value);
    partial void OnflgIsActiveChanged();
    partial void OnflgIsDeletedChanging(bool value);
    partial void OnflgIsDeletedChanged();
    partial void OnstInsUserChanging(string value);
    partial void OnstInsUserChanged();
    partial void OndtInsDateChanging(System.DateTime value);
    partial void OndtInsDateChanged();
    partial void OnstInsTermChanging(string value);
    partial void OnstInsTermChanged();
    partial void OnstUpdUserChanging(string value);
    partial void OnstUpdUserChanged();
    partial void OndtUpdDateChanging(System.Nullable<System.DateTime> value);
    partial void OndtUpdDateChanged();
    partial void OnstUpdTermChanging(string value);
    partial void OnstUpdTermChanged();
    #endregion
		
		public EntityMaster()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inEntityId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid inEntityId
		{
			get
			{
				return this._inEntityId;
			}
			set
			{
				if ((this._inEntityId != value))
				{
					this.OninEntityIdChanging(value);
					this.SendPropertyChanging();
					this._inEntityId = value;
					this.SendPropertyChanged("inEntityId");
					this.OninEntityIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_autoEntityId", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int autoEntityId
		{
			get
			{
				return this._autoEntityId;
			}
			set
			{
				if ((this._autoEntityId != value))
				{
					this.OnautoEntityIdChanging(value);
					this.SendPropertyChanging();
					this._autoEntityId = value;
					this.SendPropertyChanged("autoEntityId");
					this.OnautoEntityIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_autoEntityTypeId", DbType="Int")]
		public System.Nullable<int> autoEntityTypeId
		{
			get
			{
				return this._autoEntityTypeId;
			}
			set
			{
				if ((this._autoEntityTypeId != value))
				{
					this.OnautoEntityTypeIdChanging(value);
					this.SendPropertyChanging();
					this._autoEntityTypeId = value;
					this.SendPropertyChanged("autoEntityTypeId");
					this.OnautoEntityTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stEntityName", DbType="VarChar(150)")]
		public string stEntityName
		{
			get
			{
				return this._stEntityName;
			}
			set
			{
				if ((this._stEntityName != value))
				{
					this.OnstEntityNameChanging(value);
					this.SendPropertyChanging();
					this._stEntityName = value;
					this.SendPropertyChanged("stEntityName");
					this.OnstEntityNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stEntityCode", DbType="VarChar(150)")]
		public string stEntityCode
		{
			get
			{
				return this._stEntityCode;
			}
			set
			{
				if ((this._stEntityCode != value))
				{
					this.OnstEntityCodeChanging(value);
					this.SendPropertyChanging();
					this._stEntityCode = value;
					this.SendPropertyChanged("stEntityCode");
					this.OnstEntityCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inPEntityId", DbType="Int")]
		public System.Nullable<int> inPEntityId
		{
			get
			{
				return this._inPEntityId;
			}
			set
			{
				if ((this._inPEntityId != value))
				{
					this.OninPEntityIdChanging(value);
					this.SendPropertyChanging();
					this._inPEntityId = value;
					this.SendPropertyChanged("inPEntityId");
					this.OninPEntityIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stName", DbType="VarChar(200)")]
		public string stName
		{
			get
			{
				return this._stName;
			}
			set
			{
				if ((this._stName != value))
				{
					this.OnstNameChanging(value);
					this.SendPropertyChanging();
					this._stName = value;
					this.SendPropertyChanged("stName");
					this.OnstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stAddress", DbType="VarChar(500)")]
		public string stAddress
		{
			get
			{
				return this._stAddress;
			}
			set
			{
				if ((this._stAddress != value))
				{
					this.OnstAddressChanging(value);
					this.SendPropertyChanging();
					this._stAddress = value;
					this.SendPropertyChanged("stAddress");
					this.OnstAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inGender", DbType="Int")]
		public System.Nullable<int> inGender
		{
			get
			{
				return this._inGender;
			}
			set
			{
				if ((this._inGender != value))
				{
					this.OninGenderChanging(value);
					this.SendPropertyChanging();
					this._inGender = value;
					this.SendPropertyChanged("inGender");
					this.OninGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stEmailId", DbType="VarChar(100)")]
		public string stEmailId
		{
			get
			{
				return this._stEmailId;
			}
			set
			{
				if ((this._stEmailId != value))
				{
					this.OnstEmailIdChanging(value);
					this.SendPropertyChanging();
					this._stEmailId = value;
					this.SendPropertyChanged("stEmailId");
					this.OnstEmailIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stContactNo", DbType="VarChar(50)")]
		public string stContactNo
		{
			get
			{
				return this._stContactNo;
			}
			set
			{
				if ((this._stContactNo != value))
				{
					this.OnstContactNoChanging(value);
					this.SendPropertyChanging();
					this._stContactNo = value;
					this.SendPropertyChanged("stContactNo");
					this.OnstContactNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stFingureId", DbType="VarChar(50)")]
		public string stFingureId
		{
			get
			{
				return this._stFingureId;
			}
			set
			{
				if ((this._stFingureId != value))
				{
					this.OnstFingureIdChanging(value);
					this.SendPropertyChanging();
					this._stFingureId = value;
					this.SendPropertyChanged("stFingureId");
					this.OnstFingureIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stUserName", DbType="VarChar(150)")]
		public string stUserName
		{
			get
			{
				return this._stUserName;
			}
			set
			{
				if ((this._stUserName != value))
				{
					this.OnstUserNameChanging(value);
					this.SendPropertyChanging();
					this._stUserName = value;
					this.SendPropertyChanged("stUserName");
					this.OnstUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stPassword", DbType="VarBinary(100)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary stPassword
		{
			get
			{
				return this._stPassword;
			}
			set
			{
				if ((this._stPassword != value))
				{
					this.OnstPasswordChanging(value);
					this.SendPropertyChanging();
					this._stPassword = value;
					this.SendPropertyChanged("stPassword");
					this.OnstPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stRemark", DbType="VarChar(500)")]
		public string stRemark
		{
			get
			{
				return this._stRemark;
			}
			set
			{
				if ((this._stRemark != value))
				{
					this.OnstRemarkChanging(value);
					this.SendPropertyChanging();
					this._stRemark = value;
					this.SendPropertyChanged("stRemark");
					this.OnstRemarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dbSalary", DbType="Decimal(12,2)")]
		public System.Nullable<decimal> dbSalary
		{
			get
			{
				return this._dbSalary;
			}
			set
			{
				if ((this._dbSalary != value))
				{
					this.OndbSalaryChanging(value);
					this.SendPropertyChanging();
					this._dbSalary = value;
					this.SendPropertyChanged("dbSalary");
					this.OndbSalaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtJoiningDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> dtJoiningDate
		{
			get
			{
				return this._dtJoiningDate;
			}
			set
			{
				if ((this._dtJoiningDate != value))
				{
					this.OndtJoiningDateChanging(value);
					this.SendPropertyChanging();
					this._dtJoiningDate = value;
					this.SendPropertyChanged("dtJoiningDate");
					this.OndtJoiningDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtResignDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> dtResignDate
		{
			get
			{
				return this._dtResignDate;
			}
			set
			{
				if ((this._dtResignDate != value))
				{
					this.OndtResignDateChanging(value);
					this.SendPropertyChanging();
					this._dtResignDate = value;
					this.SendPropertyChanged("dtResignDate");
					this.OndtResignDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flgIsActive", DbType="Bit")]
		public System.Nullable<bool> flgIsActive
		{
			get
			{
				return this._flgIsActive;
			}
			set
			{
				if ((this._flgIsActive != value))
				{
					this.OnflgIsActiveChanging(value);
					this.SendPropertyChanging();
					this._flgIsActive = value;
					this.SendPropertyChanged("flgIsActive");
					this.OnflgIsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flgIsDeleted", DbType="Bit NOT NULL")]
		public bool flgIsDeleted
		{
			get
			{
				return this._flgIsDeleted;
			}
			set
			{
				if ((this._flgIsDeleted != value))
				{
					this.OnflgIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._flgIsDeleted = value;
					this.SendPropertyChanged("flgIsDeleted");
					this.OnflgIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stInsUser", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string stInsUser
		{
			get
			{
				return this._stInsUser;
			}
			set
			{
				if ((this._stInsUser != value))
				{
					this.OnstInsUserChanging(value);
					this.SendPropertyChanging();
					this._stInsUser = value;
					this.SendPropertyChanged("stInsUser");
					this.OnstInsUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtInsDate", DbType="DateTime NOT NULL")]
		public System.DateTime dtInsDate
		{
			get
			{
				return this._dtInsDate;
			}
			set
			{
				if ((this._dtInsDate != value))
				{
					this.OndtInsDateChanging(value);
					this.SendPropertyChanging();
					this._dtInsDate = value;
					this.SendPropertyChanged("dtInsDate");
					this.OndtInsDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stInsTerm", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string stInsTerm
		{
			get
			{
				return this._stInsTerm;
			}
			set
			{
				if ((this._stInsTerm != value))
				{
					this.OnstInsTermChanging(value);
					this.SendPropertyChanging();
					this._stInsTerm = value;
					this.SendPropertyChanged("stInsTerm");
					this.OnstInsTermChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stUpdUser", DbType="VarChar(50)")]
		public string stUpdUser
		{
			get
			{
				return this._stUpdUser;
			}
			set
			{
				if ((this._stUpdUser != value))
				{
					this.OnstUpdUserChanging(value);
					this.SendPropertyChanging();
					this._stUpdUser = value;
					this.SendPropertyChanged("stUpdUser");
					this.OnstUpdUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtUpdDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> dtUpdDate
		{
			get
			{
				return this._dtUpdDate;
			}
			set
			{
				if ((this._dtUpdDate != value))
				{
					this.OndtUpdDateChanging(value);
					this.SendPropertyChanging();
					this._dtUpdDate = value;
					this.SendPropertyChanged("dtUpdDate");
					this.OndtUpdDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stUpdTerm", DbType="VarChar(50)")]
		public string stUpdTerm
		{
			get
			{
				return this._stUpdTerm;
			}
			set
			{
				if ((this._stUpdTerm != value))
				{
					this.OnstUpdTermChanging(value);
					this.SendPropertyChanging();
					this._stUpdTerm = value;
					this.SendPropertyChanged("stUpdTerm");
					this.OnstUpdTermChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
